# Generated by Django 6.0.5 on 2026-05-24 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=10, unique=True)),
                ('company_code', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=3)),
                ('site_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactorRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('ef_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('fuel_type', 'region', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IATADistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('distance_km', models.IntegerField()),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP IDoc / Flat File'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Concur / Navan Travel')], max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('raw_filename', models.CharField(blank=True, max_length=255)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('staged', 'Staged for Review'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('ingested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('source_record_id', models.CharField(max_length=200)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('ghg_category', models.CharField(max_length=200)),
                ('activity_date', models.DateField()),
                ('quantity_raw', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_raw', models.CharField(max_length=20)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emission_factor_unit', models.CharField(default='kgCO2e/unit', max_length=50)),
                ('emission_factor_source', models.CharField(max_length=100)),
                ('kgco2e', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_metadata', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='emissions.emissionrecord')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'source_record_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('INGEST', 'Ingest'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('FLAG', 'Flag'), ('UNFLAG', 'Unflag'), ('EDIT', 'Edit'), ('EXPORT', 'Export')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
